language: csharp
mono: none
dotnet: 2.1.403
script:
  - dotnet restore saitech
  - dotnet build saitech
deploy:
  provider: azure_web_apps
  verbose: true
  skip_cleanup: true
git:
   depth: 9999999  